### ISSUE TITLE
Missing geometry 

### ISSUE THREAD

**Issue by DJNormality** [Kermalis/SpeedRacerTool#1]
![err](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/f81b6f83-bbed-48a8-a483-3e1ff5533768)

I cant seem to load other geometry, can you please update instructions on what to replace. I renamed my Program.cs with all my directories but still dont get all meshes. Could you assist me on how to do this ?

**Comment by Kermalis** [comment]
What kinds of models are you trying to load? For example, the props are in the `ps2_ps2\tracks\t01\models\t01ggs` folder for Thunderhead. You would use `TestNIF` in the program action and then the path would be like this one: https://github.com/Kermalis/SpeedRacerTool/blob/main/SpeedRacerTool/Program.cs#L184

**Comment by DJNormality** [comment]
![OZVZtmjMOV](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/c4f5229a-039d-48b2-b980-3cb024fcd92b)
All I keep getting is track sections in "fwd_long" folder. Anytime I change it to t01ggs it throws an error. Is there anyway you can upload these for me in a .zip ? If not I will try to change code again but im no programmer, I barely made it this far. Thank you so much for the tool I just dont understand usage too well.

**Comment by Kermalis** [comment]
I think uploading them in a zip would count as "sharing copyrighted material", so I'll have to guide you through. Luckily it should be pretty simple.
In your screenshot, add a comment (`//`) to the beginning of the `const` word at line 181. Then remove the comment at the beginning of line 184. Essentially we are swapping out which file to process.

Also make sure this line: https://github.com/Kermalis/SpeedRacerTool/blob/main/SpeedRacerTool/Program.cs#L42
Is `ProgramAction a = ProgramAction.TestNIF;`. Although I believe it already is if you managed to save the track model.

If you get any other errors, can you write what they are?

**Comment by DJNormality** [comment]
I put the // at 181 and removed them from 184 and I get this error.  Do i click debug or release ? 
![er](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/a4495ce0-fe05-4762-a2e1-8b6fe8d9bb4f)

**Comment by Kermalis** [comment]
At the top where it says "stack frame", can you show what is in the dropdown?
![image](https://github.com/Kermalis/SpeedRacerTool/assets/29823718/9fc88156-3273-4aa5-97f2-7e926e88d20c)

**Comment by DJNormality** [comment]
![devenv_iesFQXhz38](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/8602e3d9-53a5-4db8-a340-c839bdc27ba8)

**Comment by Kermalis** [comment]
I think we may have different versions of the PS2 game, which is possible. What is the CRC-32 checksum of your ISO? Mine is `738e48ca`.
If you don't know how to check that, can you tell me the exact size when you right-click the ISO and choose "properties"? Mine is this size:
![image](https://github.com/Kermalis/SpeedRacerTool/assets/29823718/738d6570-f7e5-42b1-bf11-7f9755f5cc27)

**Comment by DJNormality** [comment]
They appear to be the same. If I leave the it on 181 it will dump .obj's to folder. When I switch it to 184 it throws the error. 
![3smUI6VH2r](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/e41e6083-551f-4770-88ca-afa40285f6cb)

**Comment by Kermalis** [comment]
Hmm, I'm not sure. I'll check more in-depth maybe tomorrow. Hopefully I can get it working so we don't have to spread copyrighted material around and get in trouble for that. I'll write here if I figure anything out

**Comment by DJNormality** [comment]
If you could email me at sharppyshooter@gmail.com maybe we can work it out there, I can also share with you some other stuff I found. Im also on discord as djnormality my ID is 470715344735043587. I have tried to capture the geo with PCSX2 awhile back but it didnt have proper UV's so this would help out greatly.
![Cinema_4D_Ef23hPuO3e](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/fad534e7-e3d8-40ac-814e-303455ba4cca)

**Comment by Kermalis** [comment]
Hey, I just pushed a bunch of fixes for the PS2 props. It turns out we most likely have the same game version, but there were some changes I made previously to make the dumping more "rigid" which left these prop files not loading.

For now I added a setting that lets you proceed with dumping them even if the file isn't fully verified. (The only one that isn't fully verified after these changes is Fuji since it uses particle systems the other ones don't, and I don't feel like adding that for now)
So you can now save the meshes for all 6 PS2 tracks, just update the tool.

As for the UVs, I myself haven't fully figured out the UV data. It is clearly present in the files somewhere, but the way they stored it is super weird so I don't have a way of dumping those right now. I think the textures they used for the track are manipulated in the shader to be mirrored, since the track decorations are not mirrored. I was able to replicate this in Godot with my own textures, so that's why I say that. Maybe that's why the UVs are so weird, but either way I can't help you there right now.

Depending on the way you dumped the UVs with PCSX2, it may actually be more accurate than what I have. You would just need to set up the shader like this:
![image](https://github.com/Kermalis/SpeedRacerTool/assets/29823718/87cb2589-6165-483b-97cf-a1c0ff28c472)

I can explain it if you need me to. The `1, 0.005` is not necessary I think, so you can get away with multiplying it by `1,1` maybe.
Oh, and that multiply by 8 should be a 16

**Comment by DJNormality** [comment]
![Cinema_4D_P1aYcxpl09](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/4671a63d-1229-451d-bf07-02c34eedca03)

Still getting that error when trying to dump t01ggs.nif am i doing something wrong ? Seems the other ones are working though.
![devenv_CZe4YuIPXb](https://github.com/Kermalis/SpeedRacerTool/assets/59482618/eeae04f6-e271-4307-9fcb-78caf1c51cd9)

**Comment by Kermalis** [comment]
That error just means you put the wrong path. Judging by your other paths, it looks like you're missing a `\ps2` after the `\Speed Racer PS2`

**Comment by DJNormality** [comment]
Ah i see it now. Thank you so much for this tool. Super helpful and very useful. Thanks for all your help and the updates. I think we can close this issue now :)
